#New-API Docker组合配置
#
#快速启动：
#1。码头工人
#2.访问 http：//localhost:3000
#
#使用 MySQL
#1.注释掉 postgres您DOJ SQL_DSN 15
#2.取消 mysql you com SQL_DSN 16
#3.在取决于_you you mysql（28）
#4.在卷中取消注释 mysql网址（$64）
#
#️重要：你看，你看，你看

版本: '3.4' #与旧版 Docker

服务:
  new-api:
图像: calciumion/new-api:最近的
    container_name: new-api
重新启动: 总是
命令: --log-dir /app/logs
港口:
      - '3000:3000'
卷:
      - ./data:/data
      - ./logs:/app/logs
环境:
      - SQL_DSN=postgresql://root:123456@postgres:5432/new-api #️重要：我是马耶洛
      #-SQL_DSN=root:123456@tcp（mysql:3306）/new-api#指向 mysql mayor，you you mysql，you
      - REDIS_CONN_STRING=redis://redis
      - TZ=Asia/Shanghai
      - ERROR_LOG_ENABLED=true # 是否启用错误日志记录
      - BATCH_UPDATE_ENABLED=true #是否启用批量更新批量更新启用
    #-STREAMING_TIMEOUT=300你的流模式无响应超时时间
    #-SESSION_SECRET=random_you com多机部署时设置，you you mobie-mayou mobie-mayou mobie-mayou mobie-mayou mobie-mayou mobie-mayou mobie-mayou mobie-mayou mobie-mayou mobie，！
    #-SYNC_FREQUENCY=60#缓存同步频率；you you you

    depends_on:
      - redis
      - PostgreSQL
    #-mysql#如果使用你
健康检查:
试验:
        [
          'CMD-SHELL',
          "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\"：\\s*true"|出口 1",
        ]
间隔: 30s
超时: 10s
重试: 3

redis:
图像: redis:最近的
    container_name: redis
重新启动: 总是

PostgreSQL:
图像: PostgreSQL:15
    container_name: PostgreSQL
重新启动: 总是
环境:
      POSTGRES_USER: 根
      POSTGRES_PASSWORD: 123456 #️重要：我喜欢你的作品
      POSTGRES_DB: new-api
卷:
      - pg_data:/var/lib/postgresql/data
#端口：
#-“5432:5432”#如果需要从 Docker bostgresql

# mysql:
# image: mysql:8.2
# container_name: mysql
#重启：一直
#环境：
#MYSQL_ROOT_PASSWORD:123456#你重要：️you you mayoto mayoto mayou!
# MYSQL_DATABASE: new-api
#卷：
# - mysql_data:/var/lib/mysql
#端口：
#-“3306:3306”#如果您需要从 Docker you you MySQL

卷:
  pg_data:
# mysql_data:
