触发自动完成。要求：属实在

触发自动完成。使用

突耳使用#输入的数据类型主要的
名称：手动工作流
#控制操作何时运行，你喜欢你吗
  workflow_dispatch:
#或 API
#或 API#这是一个手动触发的基本工作流
描述：“亲切问候”
#输入工作流接受。:
输入
名字
#友好的描述将显示在 UI，you you you“name”：
“问候”
#默认值，你喜欢：“世界”
默认的
#必须为工作流的运行提供输入: 必需

真正的
#输入的数据类型：字符串:
类型
一个工作流运行由一个或多个任务组成，这些任务可以按顺序执行，也可以并行执行。
工作
    runs-on: ubuntu-latest

#这个工作流包含一个名为“问候”你：
迎接
#作业将在其上运行的运行程序类型
    - #步骤表示将作为作业的一部分执行的一系列任务：
步骤#you you:you you:echo
